services:
  peer1:
    image: prj4
    networks:
      - mynetwork
    hostname: "peer1"
    container_name: "peer1"
    command: -h hostsfile-testcase2.txt -v X

  peer2:
    image: prj4
    networks:
      - mynetwork
    hostname: "peer2"
    container_name: "peer2"
    command: -h hostsfile-testcase2.txt

  peer3:
    image: prj4
    networks:
      - mynetwork
    hostname: "peer3"
    container_name: "peer3"
    command: -h hostsfile-testcase2.txt

  peer4:
    image: prj4
    networks:
      - mynetwork
    hostname: "peer4"
    container_name: "peer4"
    command: -h hostsfile-testcase2.txt

  peer5:
    image: prj4
    networks:
      - mynetwork
    hostname: "peer5"
    container_name: "peer5"
    command: -h hostsfile-testcase2.txt -v Y -t 10

networks:
  # The presence of these objects is sufficient to define them
  mynetwork: {}
